<?php

/**
 * @file
 * An Islandora viewer module using Video.js
 */

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_videojs_islandora_viewer_info() {
  return array(
    'islandora_videojs' => array(
      'label' => t('video.js player'),
      'description' => t('video.js for video.'),
      'callback' => 'islandora_videojs_callback',
      'mimetype' => array('audio/mpeg', 'video/mp4'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_videojs_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_videojs' => array(
      'template' => 'theme/islandora-videojs',
      'variables' => array('object' => NULL, 'params' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function islandora_videojs_preprocess_islandora_videojs(array &$variables) {
  $params = $variables['params'];
  $variables['tn'] = $params['tn'];
  $videojs_path = libraries_get_path("video-js");
  drupal_add_js($videojs_path . "/video.js");
  drupal_add_css($videojs_path . '/video-js.css');

  $variables['sources'][] = array('url' => $params['url'], 'mime' => $params['mime']);
}

/**
 * Callback function to process audio player.
 *
 * @param array $params
 *   Array with configuration info for the audio player.
 */
function islandora_videojs_callback($params = array()) {
  return theme('islandora_videojs', array('params' => $params));
}
